export default class Constants {
  static MAX_NEUTRONS_ON_SCREEN = 100;
  static ATOM_RADIUS = 13;
  static WATER_SIDE = 40;
  static WATER_SEPARATION = 5;
  static NEUTRON_RADIUS = 5;
  static WATER_NEUTRON_ABSORPTION_PROBABILITY = 0.0005;
  static WATER_TEMPERATURE_INCREASE = 0.07;
  static WATER_TEMPERATURE_LOSS = 0.02;
  static XENON_DECAYMENT_PROBABILITY = 0.6;
  static HORIZONTAL_ATOMS = 40;
  static VERTICAL_ATOMS = 15;
  static URANIUM_ENRICHMENT_THRESHOLD = 0.1;
}
