export default class Constants {
  static MAX_NEUTRONS_ON_SCREEN = 50;
  static ATOM_RADIUS = 13;
  static WATER_SIDE = 40;
  static WATER_SEPARATION = 5;
  static NEUTRON_RADIUS = 5;
  static WATER_NEUTRON_ABSORPTION_PROBABILITY = 0.007;
  static WATER_HEATING_RATE = 0.4;
  static WATER_COOLING_RATE = 0.1;
  static XENON_DECAYMENT_PROBABILITY = 0.8;
  static HORIZONTAL_ATOMS = 40;
  static VERTICAL_ATOMS = 15;
  static URANIUM_ENRICHMENT_THRESHOLD = 0.1;
}
